version: "3"

services:
  app:
    volumes:
      - ./src/:/usr/app/backend-nodejs/src/
    ports:
      - 80:3333
    networks:
      ficr-network:
        ipv4_address: "192.168.42.2"
    container_name: ficr-back

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    links:
      - mongo
    restart: always
    networks:
      ficr-network:
        ipv4_address: "192.168.42.3"
    container_name: ficr-express

  mongo:
    image: mongo:4
    ports:
      - 27017:27017
    networks:
      ficr-network:
        ipv4_address: "192.168.42.4"
    container_name: ficr-mongo

networks:
  ficr-network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.42.0/24
