version: "3"

services:
  app:
    image: 253519823014.dkr.ecr.us-east-1.amazonaws.com/backend-ficr:latest
  
  mongo-express:
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ficr42
      ME_CONFIG_BASICAUTH_PASSWORD: mongoExp42
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongoadmin123
  
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=mongoadmin123